theme: jekyll-theme-minimal

# Site settings
title: Ivana Jones
email: ivanajns@gmail.com
description: "Sr Developer - RPA, BI, and Finance Transformation"


# Team names, titles and social links
people:
- name: Ivana Jones
  pic: 1
  position: Sr Developer - RPA, BI, and Finance Transformation
  social:
    - title: messenger
      url: mailto:ivanajns@gmail.com
    - title: linkedin
      url: https://www.linkedin.com/in/ivanajns
    - title: facebook
      url: https://www.facebook.com/ivanajnsx
